import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Plus, Download, Calendar, DollarSign, Calculator, Printer, FileText, TrendingUp, Zap, Eye, Check, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Checkbox } from "@/components/ui/checkbox";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { insertPayslipSchema, type Employee, type Payslip, type InsertPayslip, type PayslipCalculation } from "@shared/schema";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import BackToMenuButton from "@/components/BackToMenuButton";

interface PayslipPreview {
  employee: Employee;
  payslip: Omit<InsertPayslip, 'employeePassport'> & { calculations: PayslipCalculation };
}

export default function Payslips() {
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isAutogenerateDialogOpen, setIsAutogenerateDialogOpen] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState<Employee | null>(null);
  const [calculations, setCalculations] = useState<PayslipCalculation | null>(null);
  const [selectedReportMonth, setSelectedReportMonth] = useState<string>(new Date().toISOString().slice(0, 7));
  const [payslipPreviews, setPayslipPreviews] = useState<PayslipPreview[]>([]);
  const [selectedPayslips, setSelectedPayslips] = useState<Set<string>>(new Set());
  const [autogenerateData, setAutogenerateData] = useState({
    payPeriod: new Date().toISOString().slice(0, 7),
    payDate: new Date().toISOString().slice(0, 10),
  });
  const queryClient = useQueryClient();
  const { toast } = useToast();

  const { data: employees = [] } = useQuery<Employee[]>({
    queryKey: ["/api/employees"],
  });

  const { data: payslips = [], isLoading } = useQuery<Payslip[]>({
    queryKey: ["/api/payslips"],
  });

  const createMutation = useMutation({
    mutationFn: (data: InsertPayslip) => apiRequest("/api/payslips", "POST", data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/payslips"] });
      setIsDialogOpen(false);
      setSelectedEmployee(null);
      setCalculations(null);
      toast({ title: "Success", description: "Payslip created successfully" });
    },
    onError: (error: any) => {
      toast({ title: "Error", description: error.message, variant: "destructive" });
    },
  });

  const previewMutation = useMutation({
    mutationFn: async (data: { payPeriod: string; payDate: string }) => {
      try {
        const result = await apiRequest("/api/payslips/preview", "POST", data);
        return result as unknown as PayslipPreview[];
      } catch (error) {
        console.error("Preview mutation error:", error);
        throw error;
      }
    },
    onSuccess: (data: any) => {
      console.log("Preview data received:", data);
      console.log("Data type:", typeof data);
      console.log("Is array:", Array.isArray(data));
      
      const previewData = Array.isArray(data) ? data : [];
      console.log("Preview data length:", previewData.length);
      
      setPayslipPreviews(previewData);
      setSelectedPayslips(new Set(previewData.map(p => p.employee.passport)));
      
      if (previewData.length === 0) {
        toast({ 
          title: "No Payslips to Generate", 
          description: `All active employees already have payslips for ${autogenerateData.payPeriod} or no active employees found. Try selecting a different month.`,
          variant: "default"
        });
      } else {
        toast({ 
          title: "Preview Generated", 
          description: `Found ${previewData.length} employees eligible for payslips.`,
          variant: "default"
        });
      }
    },
    onError: (error: any) => {
      console.error("Preview error:", error);
      toast({ title: "Error", description: error.message || "Failed to generate preview", variant: "destructive" });
    },
  });

  const bulkCreateMutation = useMutation({
    mutationFn: async (payslipData: Array<{ employeePassport: string; payPeriod: string; payDate: string; grossSalary: number; notes?: string }>) => {
      const result = await apiRequest("/api/payslips/bulk", "POST", { payslips: payslipData });
      return result as unknown as Payslip[];
    },
    onSuccess: (data: Payslip[]) => {
      queryClient.invalidateQueries({ queryKey: ["/api/payslips"] });
      setIsAutogenerateDialogOpen(false);
      setPayslipPreviews([]);
      setSelectedPayslips(new Set());
      toast({ 
        title: "Success", 
        description: `${data.length} payslips created successfully` 
      });
    },
    onError: (error: any) => {
      toast({ title: "Error", description: error.message, variant: "destructive" });
    },
  });

  const form = useForm<InsertPayslip>({
    resolver: zodResolver(insertPayslipSchema),
    defaultValues: {
      employeePassport: "",
      payPeriod: new Date().toISOString().slice(0, 7), // YYYY-MM format
      payDate: new Date().toISOString().slice(0, 10), // YYYY-MM-DD format
      grossSalary: 0,
      notes: "",
    },
  });

  const grossSalary = form.watch("grossSalary");

  // Calculate deductions in real-time
  const calculateDeductions = async (salary: number) => {
    if (salary > 0) {
      try {
        const result = await apiRequest("/api/payslips/calculate", "POST", { grossSalary: salary });
        setCalculations(result as unknown as PayslipCalculation);
      } catch (error) {
        console.error("Error calculating deductions:", error);
      }
    } else {
      setCalculations(null);
    }
  };

  const onSubmit = (data: InsertPayslip) => {
    // Convert salary to cents for storage
    const salaryInCents = Math.round(data.grossSalary * 100);
    const payslipData = { ...data, grossSalary: salaryInCents };
    createMutation.mutate(payslipData);
  };

  const handleEmployeeChange = (employeePassport: string) => {
    const employee = employees.find((emp: Employee) => emp.passport === employeePassport);
    setSelectedEmployee(employee || null);
    
    if (employee) {
      // Pre-fill with employee's monthly salary
      const salaryInEuros = employee.monthlySalary / 100;
      form.setValue("grossSalary", salaryInEuros);
      calculateDeductions(salaryInEuros);
    }
  };

  const handleCreate = () => {
    form.reset({
      employeePassport: "",
      payPeriod: new Date().toISOString().slice(0, 7),
      payDate: new Date().toISOString().slice(0, 10),
      grossSalary: 0,
      notes: "",
    });
    setSelectedEmployee(null);
    setCalculations(null);
    setIsDialogOpen(true);
  };

  const handleAutogenerate = () => {
    setAutogenerateData({
      payPeriod: new Date().toISOString().slice(0, 7),
      payDate: new Date().toISOString().slice(0, 10),
    });
    setPayslipPreviews([]);
    setSelectedPayslips(new Set());
    setIsAutogenerateDialogOpen(true);
  };

  const handleGeneratePreview = () => {
    previewMutation.mutate(autogenerateData);
  };

  const handleTogglePayslip = (employeePassport: string) => {
    const newSelected = new Set(selectedPayslips);
    if (newSelected.has(employeePassport)) {
      newSelected.delete(employeePassport);
    } else {
      newSelected.add(employeePassport);
    }
    setSelectedPayslips(newSelected);
  };

  const handleToggleAll = () => {
    if (selectedPayslips.size === payslipPreviews.length) {
      setSelectedPayslips(new Set());
    } else {
      setSelectedPayslips(new Set(payslipPreviews.map(p => p.employee.passport)));
    }
  };

  const handleCreateSelectedPayslips = () => {
    const selectedPreviewData = payslipPreviews
      .filter(preview => selectedPayslips.has(preview.employee.passport))
      .map(preview => ({
        employeePassport: preview.employee.passport,
        payPeriod: preview.payslip.payPeriod,
        payDate: preview.payslip.payDate,
        grossSalary: preview.payslip.grossSalary,
        notes: preview.payslip.notes || undefined,
      }));

    if (selectedPreviewData.length === 0) {
      toast({ 
        title: "Warning", 
        description: "Please select at least one payslip to create",
        variant: "destructive"
      });
      return;
    }

    bulkCreateMutation.mutate(selectedPreviewData);
  };

  const formatCurrency = (cents: number) => {
    return `€${(cents / 100).toFixed(2)}`;
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString();
  };

  const formatPeriod = (period: string) => {
    const [year, month] = period.split('-');
    const date = new Date(parseInt(year), parseInt(month) - 1);
    return date.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
  };

  const getEmployeeName = (employeePassport: string) => {
    const employee = employees.find((emp: Employee) => emp.passport === employeePassport);
    return employee?.name || 'Unknown Employee';
  };

  // Group payslips by employee
  const payslipsByEmployee = payslips.reduce((acc: Record<string, Payslip[]>, payslip: Payslip) => {
    if (!acc[payslip.employeePassport]) {
      acc[payslip.employeePassport] = [];
    }
    acc[payslip.employeePassport].push(payslip);
    return acc;
  }, {});

  // Filter payslips by selected month for monthly report
  const getPayslipsForMonth = (month: string) => {
    return payslips.filter(payslip => payslip.payPeriod === month);
  };

  // Calculate monthly totals
  const calculateMonthlyTotals = (monthPayslips: Payslip[]) => {
    return monthPayslips.reduce((totals, payslip) => {
      return {
        totalGrossSalary: totals.totalGrossSalary + payslip.grossSalary,
        totalSocialInsurance: totals.totalSocialInsurance + payslip.socialInsurance,
        totalGesy: totals.totalGesy + payslip.gesy,
        totalDeductions: totals.totalDeductions + payslip.totalDeductions,
        totalNetPay: totals.totalNetPay + payslip.netPay,
        employeeCount: monthPayslips.length,
      };
    }, {
      totalGrossSalary: 0,
      totalSocialInsurance: 0,
      totalGesy: 0,
      totalDeductions: 0,
      totalNetPay: 0,
      employeeCount: 0,
    });
  };

  // Get unique months from payslips for dropdown
  const getAvailableMonths = () => {
    const uniqueMonths = new Set(payslips.map(p => p.payPeriod));
    const months = Array.from(uniqueMonths);
    return months.sort().reverse(); // Latest months first
  };

  const monthlyPayslips = getPayslipsForMonth(selectedReportMonth);
  const monthlyTotals = calculateMonthlyTotals(monthlyPayslips);

  if (isLoading) {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h1 className="text-3xl font-bold tracking-tight">Payslips</h1>
        </div>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {[1, 2, 3].map((i) => (
            <Card key={i} className="animate-pulse">
              <CardHeader className="space-y-2">
                <div className="h-4 bg-gray-200 rounded w-3/4"></div>
                <div className="h-3 bg-gray-200 rounded w-1/2"></div>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <div className="h-3 bg-gray-200 rounded"></div>
                  <div className="h-3 bg-gray-200 rounded w-2/3"></div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <BackToMenuButton />
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Payslip Management</h1>
          <p className="text-muted-foreground">
            Generate payslips with automatic Cyprus deduction calculations and monthly reports
          </p>
        </div>
        <div className="flex gap-2">
          <Button onClick={handleCreate} className="flex items-center gap-2">
            <Plus className="h-4 w-4" />
            Generate Payslip
          </Button>
          <Button onClick={handleAutogenerate} variant="outline" className="flex items-center gap-2">
            <Zap className="h-4 w-4" />
            Auto-Generate Monthly Payslips
          </Button>
        </div>
      </div>

      <Tabs defaultValue="payslips" className="space-y-6">
        <TabsList className="grid w-full max-w-md grid-cols-2">
          <TabsTrigger value="payslips" className="flex items-center gap-2">
            <Calculator className="h-4 w-4" />
            Payslips
          </TabsTrigger>
          <TabsTrigger value="reports" className="flex items-center gap-2">
            <FileText className="h-4 w-4" />
            Monthly Reports
          </TabsTrigger>
        </TabsList>

        <TabsContent value="payslips" className="space-y-6">
          {/* Recent Payslips */}
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {payslips.slice(0, 6).map((payslip: Payslip) => (
              <Card key={payslip.id}>
                <CardHeader className="pb-3">
                  <div className="flex items-start justify-between">
                    <div className="space-y-1">
                      <CardTitle className="text-lg">{getEmployeeName(payslip.employeePassport)}</CardTitle>
                      <p className="text-sm text-muted-foreground">{formatPeriod(payslip.payPeriod)}</p>
                    </div>
                    <Badge variant="outline">
                      {formatDate(payslip.payDate)}
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent className="space-y-3">
                  <div className="space-y-2 text-sm">
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Gross Salary:</span>
                      <span className="font-medium">{formatCurrency(payslip.grossSalary)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Social Insurance:</span>
                      <span className="text-red-600">-{formatCurrency(payslip.socialInsurance)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">GESY:</span>
                      <span className="text-red-600">-{formatCurrency(payslip.gesy)}</span>
                    </div>
                    <div className="border-t pt-2 flex justify-between font-semibold">
                      <span>Net Pay:</span>
                      <span className="text-green-600">{formatCurrency(payslip.netPay)}</span>
                    </div>
                  </div>

                  <div className="flex gap-2">
                    <Button 
                      variant="outline" 
                      size="sm" 
                      className="flex-1"
                      onClick={() => window.open(`/api/payslips/${payslip.id}/pdf`, '_blank')}
                    >
                      <Download className="h-3 w-3 mr-2" />
                      Download
                    </Button>
                    <Button 
                      variant="outline" 
                      size="sm" 
                      className="flex-1"
                      onClick={() => {
                        const printWindow = window.open(`/api/payslips/${payslip.id}/pdf`, '_blank');
                        if (printWindow) {
                          printWindow.onload = () => {
                            printWindow.print();
                          };
                        }
                      }}
                    >
                      <Printer className="h-3 w-3 mr-2" />
                      Print
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          {payslips.length === 0 && (
            <Card className="text-center py-12">
              <CardContent>
                <Calculator className="mx-auto h-12 w-12 text-muted-foreground mb-4" />
                <h3 className="text-lg font-semibold mb-2">No payslips found</h3>
                <p className="text-muted-foreground mb-4">
                  Generate your first payslip with automatic Cyprus deduction calculations.
                </p>
                <Button onClick={handleCreate}>
                  <Plus className="h-4 w-4 mr-2" />
                  Generate Payslip
                </Button>
              </CardContent>
            </Card>
          )}

          {/* Payslips by Employee */}
          {Object.keys(payslipsByEmployee).length > 0 && (
            <div className="space-y-4">
              <h2 className="text-xl font-semibold">Payslips by Employee</h2>
              {Object.entries(payslipsByEmployee).map(([employeePassport, employeePayslips]) => (
                <Card key={employeePassport}>
                  <CardHeader>
                    <CardTitle className="text-lg">{getEmployeeName(employeePassport)}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-2">
                      {employeePayslips.map((payslip) => (
                        <div key={payslip.id} className="flex items-center justify-between p-3 border rounded-lg">
                          <div className="flex items-center gap-3">
                            <Calendar className="h-4 w-4 text-muted-foreground" />
                            <div>
                              <p className="font-medium">{formatPeriod(payslip.payPeriod)}</p>
                              <p className="text-sm text-muted-foreground">Paid on {formatDate(payslip.payDate)}</p>
                            </div>
                          </div>
                          <div className="flex items-center gap-3">
                            <div className="text-right">
                              <p className="font-semibold text-green-600">{formatCurrency(payslip.netPay)}</p>
                              <p className="text-xs text-muted-foreground">Net Pay</p>
                            </div>
                            <div className="flex gap-1">
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() => window.open(`/api/payslips/${payslip.id}/pdf`, '_blank')}
                              >
                                <Download className="h-3 w-3" />
                              </Button>
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() => {
                                  const printWindow = window.open(`/api/payslips/${payslip.id}/pdf`, '_blank');
                                  if (printWindow) {
                                    printWindow.onload = () => {
                                      printWindow.print();
                                    };
                                  }
                                }}
                              >
                                <Printer className="h-3 w-3" />
                              </Button>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </TabsContent>

        <TabsContent value="reports" className="space-y-6">
          {/* Monthly Report Section */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <TrendingUp className="h-5 w-5" />
                Monthly Salary Report
              </CardTitle>
              <p className="text-sm text-muted-foreground">
                View net salary payments and totals for a specific month
              </p>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center gap-4">
                <div className="flex-1 max-w-xs">
                  <label htmlFor="month-select" className="block text-sm font-medium mb-2">
                    Select Month
                  </label>
                  <Select value={selectedReportMonth} onValueChange={setSelectedReportMonth}>
                    <SelectTrigger id="month-select">
                      <SelectValue placeholder="Select month" />
                    </SelectTrigger>
                    <SelectContent>
                      {getAvailableMonths().map((month) => (
                        <SelectItem key={month} value={month}>
                          {formatPeriod(month)}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <Button 
                  variant="outline"
                  onClick={() => {
                    const url = `/api/reports/monthly-payroll?month=${selectedReportMonth}`;
                    window.open(url, '_blank');
                  }}
                  className="mt-6"
                >
                  <Download className="h-4 w-4 mr-2" />
                  Export PDF
                </Button>
              </div>

              {monthlyPayslips.length > 0 ? (
                <div className="space-y-6">
                  {/* Summary Cards */}
                  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
                    <Card>
                      <CardContent className="p-4">
                        <div className="flex items-center gap-2">
                          <DollarSign className="h-4 w-4 text-green-600" />
                          <div>
                            <p className="text-sm text-muted-foreground">Total Net Pay</p>
                            <p className="text-2xl font-bold text-green-600">{formatCurrency(monthlyTotals.totalNetPay)}</p>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                    <Card>
                      <CardContent className="p-4">
                        <div className="flex items-center gap-2">
                          <DollarSign className="h-4 w-4 text-blue-600" />
                          <div>
                            <p className="text-sm text-muted-foreground">Total Gross Pay</p>
                            <p className="text-2xl font-bold">{formatCurrency(monthlyTotals.totalGrossSalary)}</p>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                    <Card>
                      <CardContent className="p-4">
                        <div className="flex items-center gap-2">
                          <DollarSign className="h-4 w-4 text-red-600" />
                          <div>
                            <p className="text-sm text-muted-foreground">Total Deductions</p>
                            <p className="text-2xl font-bold text-red-600">{formatCurrency(monthlyTotals.totalDeductions)}</p>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                    <Card>
                      <CardContent className="p-4">
                        <div className="flex items-center gap-2">
                          <Calendar className="h-4 w-4 text-purple-600" />
                          <div>
                            <p className="text-sm text-muted-foreground">Employees Paid</p>
                            <p className="text-2xl font-bold">{monthlyTotals.employeeCount}</p>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  </div>

                  {/* Detailed Breakdown */}
                  <Card>
                    <CardHeader>
                      <CardTitle>Salary Breakdown for {formatPeriod(selectedReportMonth)}</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-3">
                        {monthlyPayslips.map((payslip) => (
                          <div key={payslip.id} className="flex items-center justify-between p-4 border rounded-lg">
                            <div className="flex items-center gap-4">
                              <div>
                                <p className="font-semibold">{getEmployeeName(payslip.employeePassport)}</p>
                                <p className="text-sm text-muted-foreground">
                                  Paid on {formatDate(payslip.payDate)}
                                </p>
                              </div>
                            </div>
                            <div className="text-right">
                              <div className="grid grid-cols-3 gap-6 text-sm">
                                <div>
                                  <p className="text-muted-foreground">Gross</p>
                                  <p className="font-medium">{formatCurrency(payslip.grossSalary)}</p>
                                </div>
                                <div>
                                  <p className="text-muted-foreground">Deductions</p>
                                  <p className="font-medium text-red-600">-{formatCurrency(payslip.totalDeductions)}</p>
                                </div>
                                <div>
                                  <p className="text-muted-foreground">Net Pay</p>
                                  <p className="font-semibold text-green-600">{formatCurrency(payslip.netPay)}</p>
                                </div>
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                </div>
              ) : (
                <Card className="text-center py-12">
                  <CardContent>
                    <FileText className="mx-auto h-12 w-12 text-muted-foreground mb-4" />
                    <h3 className="text-lg font-semibold mb-2">No payslips found</h3>
                    <p className="text-muted-foreground">
                      No payslips were generated for {formatPeriod(selectedReportMonth)}
                    </p>
                  </CardContent>
                </Card>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>Generate New Payslip</DialogTitle>
          </DialogHeader>

          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
              <FormField
                control={form.control}
                name="employeePassport"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Employee *</FormLabel>
                    <Select onValueChange={(value) => {
                      field.onChange(value);
                      handleEmployeeChange(value);
                    }}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Select employee" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {employees.map((employee: Employee) => (
                          <SelectItem key={employee.passport} value={employee.passport}>
                            {employee.name} - {employee.designation}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <div className="grid grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="payPeriod"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Pay Period *</FormLabel>
                      <FormControl>
                        <Input type="month" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="payDate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Pay Date *</FormLabel>
                      <FormControl>
                        <Input type="date" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <FormField
                control={form.control}
                name="grossSalary"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Gross Salary (€) *</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        step="0.01"
                        min="0"
                        placeholder="465.00"
                        {...field}
                        onChange={(e) => {
                          const value = parseFloat(e.target.value) || 0;
                          field.onChange(value);
                          calculateDeductions(value);
                        }}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Real-time Calculation Display */}
              {calculations && (
                <Card className="bg-muted/50">
                  <CardHeader className="pb-3">
                    <CardTitle className="text-sm flex items-center gap-2">
                      <Calculator className="h-4 w-4" />
                      Deduction Breakdown
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-2 text-sm">
                    <div className="flex justify-between">
                      <span>Gross Salary:</span>
                      <span className="font-medium">€{calculations?.grossSalary?.toFixed(2) || '0.00'}</span>
                    </div>
                    <div className="flex justify-between text-red-600">
                      <span>Social Insurance (8.3%):</span>
                      <span>-€{calculations?.socialInsurance?.toFixed(2) || '0.00'}</span>
                    </div>
                    <div className="flex justify-between text-red-600">
                      <span>GESY (2.65%):</span>
                      <span>-€{calculations?.gesy?.toFixed(2) || '0.00'}</span>
                    </div>
                    <div className="border-t pt-2 flex justify-between font-semibold text-green-600">
                      <span>Net Pay:</span>
                      <span>€{calculations?.netPay?.toFixed(2) || '0.00'}</span>
                    </div>
                  </CardContent>
                </Card>
              )}

              <FormField
                control={form.control}
                name="notes"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Notes</FormLabel>
                    <FormControl>
                      <Input placeholder="Optional notes" {...field} value={field.value || ""} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <div className="flex gap-2 pt-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setIsDialogOpen(false)}
                  className="flex-1"
                >
                  Cancel
                </Button>
                <Button
                  type="submit"
                  disabled={createMutation.isPending || !selectedEmployee}
                  className="flex-1"
                >
                  {createMutation.isPending ? "Generating..." : "Generate Payslip"}
                </Button>
              </div>
            </form>
          </Form>
        </DialogContent>
      </Dialog>

      {/* Auto-generate Payslips Dialog */}
      <Dialog open={isAutogenerateDialogOpen} onOpenChange={setIsAutogenerateDialogOpen}>
        <DialogContent className="sm:max-w-4xl">
          <DialogHeader>
            <DialogTitle>Auto-Generate Monthly Payslips</DialogTitle>
          </DialogHeader>

          <div className="space-y-6">
            {/* Date Selection */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-sm font-medium mb-2 block">Pay Period</label>
                <Input
                  type="month"
                  value={autogenerateData.payPeriod}
                  onChange={(e) => setAutogenerateData(prev => ({ ...prev, payPeriod: e.target.value }))}
                />
              </div>
              <div>
                <label className="text-sm font-medium mb-2 block">Pay Date</label>
                <Input
                  type="date"
                  value={autogenerateData.payDate}
                  onChange={(e) => setAutogenerateData(prev => ({ ...prev, payDate: e.target.value }))}
                />
              </div>
            </div>

            {/* Generate Preview Button */}
            <Button 
              onClick={handleGeneratePreview}
              disabled={previewMutation.isPending}
              className="w-full"
            >
              <Eye className="h-4 w-4 mr-2" />
              {previewMutation.isPending ? "Generating Preview..." : "Generate Preview"}
            </Button>

            {/* Preview Table */}
            {payslipPreviews.length > 0 && (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-semibold">Payslip Preview</h3>
                  <div className="flex items-center gap-2">
                    <Checkbox
                      checked={selectedPayslips.size === payslipPreviews.length}
                      onCheckedChange={handleToggleAll}
                    />
                    <span className="text-sm text-muted-foreground">
                      Select All ({selectedPayslips.size}/{payslipPreviews.length})
                    </span>
                  </div>
                </div>

                <div className="border rounded-lg overflow-hidden">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead className="w-12">Select</TableHead>
                        <TableHead>Employee</TableHead>
                        <TableHead>Designation</TableHead>
                        <TableHead className="text-right">Gross Salary</TableHead>
                        <TableHead className="text-right">Social Insurance</TableHead>
                        <TableHead className="text-right">GESY</TableHead>
                        <TableHead className="text-right">Net Pay</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {payslipPreviews.map((preview) => (
                        <TableRow key={preview.employee.passport}>
                          <TableCell>
                            <Checkbox
                              checked={selectedPayslips.has(preview.employee.passport)}
                              onCheckedChange={() => handleTogglePayslip(preview.employee.passport)}
                            />
                          </TableCell>
                          <TableCell className="font-medium">{preview.employee.name}</TableCell>
                          <TableCell>{preview.employee.designation}</TableCell>
                          <TableCell className="text-right">
                            €{preview.payslip.calculations.grossSalary.toFixed(2)}
                          </TableCell>
                          <TableCell className="text-right text-red-600">
                            -€{preview.payslip.calculations.socialInsurance.toFixed(2)}
                          </TableCell>
                          <TableCell className="text-right text-red-600">
                            -€{preview.payslip.calculations.gesy.toFixed(2)}
                          </TableCell>
                          <TableCell className="text-right font-semibold text-green-600">
                            €{preview.payslip.calculations.netPay.toFixed(2)}
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>

                {/* Summary */}
                <Card className="bg-muted/50">
                  <CardContent className="pt-6">
                    <div className="grid grid-cols-4 gap-4 text-center">
                      <div>
                        <p className="text-sm text-muted-foreground">Selected Employees</p>
                        <p className="text-2xl font-bold">{selectedPayslips.size}</p>
                      </div>
                      <div>
                        <p className="text-sm text-muted-foreground">Total Gross</p>
                        <p className="text-2xl font-bold">
                          €{payslipPreviews
                            .filter(p => selectedPayslips.has(p.employee.passport))
                            .reduce((sum, p) => sum + p.payslip.calculations.grossSalary, 0)
                            .toFixed(2)}
                        </p>
                      </div>
                      <div>
                        <p className="text-sm text-muted-foreground">Total Deductions</p>
                        <p className="text-2xl font-bold text-red-600">
                          -€{payslipPreviews
                            .filter(p => selectedPayslips.has(p.employee.passport))
                            .reduce((sum, p) => sum + p.payslip.calculations.totalDeductions, 0)
                            .toFixed(2)}
                        </p>
                      </div>
                      <div>
                        <p className="text-sm text-muted-foreground">Total Net Pay</p>
                        <p className="text-2xl font-bold text-green-600">
                          €{payslipPreviews
                            .filter(p => selectedPayslips.has(p.employee.passport))
                            .reduce((sum, p) => sum + p.payslip.calculations.netPay, 0)
                            .toFixed(2)}
                        </p>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Action Buttons */}
                <div className="flex gap-2 pt-4">
                  <Button
                    variant="outline"
                    onClick={() => setIsAutogenerateDialogOpen(false)}
                    className="flex-1"
                  >
                    <X className="h-4 w-4 mr-2" />
                    Cancel
                  </Button>
                  <Button
                    onClick={handleCreateSelectedPayslips}
                    disabled={bulkCreateMutation.isPending || selectedPayslips.size === 0}
                    className="flex-1"
                  >
                    <Check className="h-4 w-4 mr-2" />
                    {bulkCreateMutation.isPending 
                      ? "Creating Payslips..." 
                      : `Create ${selectedPayslips.size} Payslips`
                    }
                  </Button>
                </div>
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}